[build.environment]
  NODE_VERSION = "12"
  NPM_VERSION = "6"

[[redirects]]
  from = "/join"
  to = "https://discord.gg/239EP7G"
  status = 302

[[redirects]]
  from = "/admin"
  to = "https://domaincord.sanity.com/"
  status = 301
