name: Build and Deploy
on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd web && npm install
      - name: set staging environment variables
        uses: allenevans/set-env@v1.1.0
        if: github.ref == 'refs/heads/dev'
        with: 
          PROJECT_ID: 'dncord-beta'
          BUILD_CMD: 'npm run build:staging'
      - name: set production environment variables
        uses: allenevans/set-env@v1.1.0
        if: github.ref == 'refs/heads/master'
        with: 
          PROJECT_ID: 'dncord-fb94e'
          BUILD_CMD: 'npm run build'
      - name: Build
        run: ${BUILD_CMD}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: web/public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:org
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${PROJECT_ID}
